server:
  port: 8082 # Укажите уникальный порт для каждого сервиса

spring:
  application:
    name: transaction-service # Уникальное имя для сервиса
  datasource:
    url: jdbc:postgresql://localhost:5433/transaction_db
    username: postgres
    password: airat020660
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Убедитесь, что схема базы данных будет обновляться автоматически
    show-sql: true # Логирование SQL-запросов для отладки
    dialect: org.hibernate.dialect.PostgreSQL10Dialect

logging:
  level:
    org.springframework: INFO